### ISSUE TITLE
Doesn't install via phar, nor the Laravel service provider

### ISSUE THREAD

**Issue by EwanValentine** [rocketeers/rocketeer#571]
Both complain that the dependencies are out of date. 

```
Changed current directory to /Users/ewanvalentine/.composer
Using version ^2.2 for anahkiasen/rocketeer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for anahkiasen/rocketeer ^2.2 -> satisfiable by anahkiasen/rocketeer[2.2.0].
    - Conclusion: remove symfony/console v2.6.1
    - Conclusion: don't install symfony/console v2.6.1
    - anahkiasen/rocketeer 2.2.0 requires illuminate/console ~4.2 -> satisfiable by illuminate/console[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - illuminate/console v4.2.1 requires symfony/console 2.5.* -> satisfiable by symfony/console[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - illuminate/console v4.2.12 requires symfony/console 2.5.* -> satisfiable by symfony/console[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - illuminate/console v4.2.16 requires symfony/console 2.5.* -> satisfiable by symfony/console[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - illuminate/console v4.2.17 requires symfony/console 2.5.* -> satisfiable by symfony/console[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - illuminate/console v4.2.2 requires symfony/console 2.5.* -> satisfiable by symfony/console[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - illuminate/console v4.2.3 requires symfony/console 2.5.* -> satisfiable by symfony/console[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - illuminate/console v4.2.4 requires symfony/console 2.5.* -> satisfiable by symfony/console[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - illuminate/console v4.2.5 requires symfony/console 2.5.* -> satisfiable by symfony/console[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - illuminate/console v4.2.6 requires symfony/console 2.5.* -> satisfiable by symfony/console[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - illuminate/console v4.2.7 requires symfony/console 2.5.* -> satisfiable by symfony/console[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - illuminate/console v4.2.8 requires symfony/console 2.5.* -> satisfiable by symfony/console[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - illuminate/console v4.2.9 requires symfony/console 2.5.* -> satisfiable by symfony/console[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - Can only install one of: symfony/console[v2.5.0, v2.6.1].
    - Can only install one of: symfony/console[v2.5.1, v2.6.1].
    - Can only install one of: symfony/console[v2.5.10, v2.6.1].
    - Can only install one of: symfony/console[v2.5.11, v2.6.1].
    - Can only install one of: symfony/console[v2.5.12, v2.6.1].
    - Can only install one of: symfony/console[v2.5.2, v2.6.1].
    - Can only install one of: symfony/console[v2.5.3, v2.6.1].
    - Can only install one of: symfony/console[v2.5.4, v2.6.1].
    - Can only install one of: symfony/console[v2.5.5, v2.6.1].
    - Can only install one of: symfony/console[v2.5.6, v2.6.1].
    - Can only install one of: symfony/console[v2.5.7, v2.6.1].
    - Can only install one of: symfony/console[v2.5.8, v2.6.1].
    - Can only install one of: symfony/console[v2.5.9, v2.6.1].
    - Installation request for symfony/console == 2.6.1.0 -> satisfiable by symfony/console[v2.6.1].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by Anahkiasen** [comment]
As answered in the other issue you're confusing the PHAR with installing Rocketeer globally. [This is the PHAR installation](https://github.com/rocketeers/rocketeer/blob/master/README.md#installation)

**Comment by clphillips** [comment]
Why is the PHAR always out of date? Current version at that URL is 2.1.2 (Mar 10, 2015). Current release is 2.2.0 (Apr 4, 2015).

**Comment by BafS** [comment]
Yes, the phar is out of date. Please update it.

**Comment by Anahkiasen** [comment]
@BafS What version are you requiring and on which version of Laravel?

**Comment by BafS** [comment]
The phar is version 2.1.2 but the last version is 2.2.2.

I use laravel 5.2 and I cannot install rockeeter via composer because of conflicts.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.2.39
    - Conclusion: don't install laravel/framework v5.2.39
    - anahkiasen/rocketeer 2.2.0 requires illuminate/log ~4.2 -> satisfiable by illuminate/log[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - anahkiasen/rocketeer 2.2.1 requires illuminate/log ~4.2 -> satisfiable by illuminate/log[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - anahkiasen/rocketeer 2.2.2 requires illuminate/log ~4.2 -> satisfiable by illuminate/log[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
...
```

Also I use PHP 7 and I have a lot of errors with rocketeer 2.1.2, that's why an updated far seems a good solution imho.

**Comment by Anahkiasen** [comment]
It should regenerate every night, seems there was a bug in the PHAR generation command, looking into it right now

**Comment by Anahkiasen** [comment]
Fixed

```
$ wget http://rocketeer.autopergamene.eu/versions/rocketeer.phar && php rocketeer.phar
Rocketeer version 2.2.1
```

**Comment by Anahkiasen** [comment]
And I just noticed I forgot to update the version again. I will forever curse the 2.x branch for that

**Comment by BafS** [comment]
Thank you for you reactivity, it works !

I still have a lot of messages (depreciations) because of dependencies but that's an other issue.

```
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Net_SFTP has a deprecated constructor in phar:///usr/local/bin/rocketeer/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php on line 122
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/rocketeer:0
PHP   2. require() /usr/local/bin/rocketeer:16
PHP   3. Illuminate\Support\Facades\Facade::run() phar:///usr/local/bin/rocketeer/bin/rocketeer:26
...
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Crypt_Base has a deprecated constructor in phar:///usr/local/bin/rocketeer/vendor/phpseclib/phpseclib/phpseclib/Crypt/Base.php on line 121
...
```

**Comment by Anahkiasen** [comment]
Yes unfortunately since Rocketeer 2.x is stuck on outdated Illuminate components I can't update them for PHP compatibility. But I'm making good progress on Rocketeer 3 so hopefully I should be able to get it out soon

**Comment by BafS** [comment]
Yes I see, good luck then :)
